import Head from 'next/head';
import { useState } from 'react';
import { useSelector } from 'react-redux';
import AdminLogin from '../../components/Admin/AdminLogin';
import ImageUpload from '../../components/Admin/ImageUpload';
import Header from '../../components/HeaderFooter/Header';
import { selectPerson } from '../../slices/personStateSlice';

function index() {
  const dataSlice = useSelector(selectPerson);
  const [show, setShow] = useState(dataSlice?.email);

  return (
    <div>
      <Head>
        <title>Admin Panel</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <AdminLogin />
    </div>
  );
}

export default index;
