import Head from 'next/head';
import Header from '../../components/HeaderFooter/Header';
import WheelsList from '../../components/Wheels/WheelsList';
import WheelsSelection from '../../components/Wheels/WheelsSelection';
import styles from '../../styles/Wheels/Wheels.module.css';
import Footer from '../../components/HeaderFooter/Footer';

function wheels() {
  return (
    <div>
      <Head>
        <title>Wheels - Wise Wheels</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <Header />
        <div className={styles.body}>
          <WheelsSelection />
          <WheelsList />
        </div>
        <Footer />
      </main>
    </div>
  );
}

export default wheels;
