import Head from 'next/head';
import Image from 'next/image';
import { useRouter } from 'next/router';
import Footer from '../../components/HeaderFooter/Footer';
import Header from '../../components/HeaderFooter/Header';
import styles from '../../styles/Wheels/wheelDetail.module.css';

function wheel() {
  const router = useRouter();
  const { id, picture, name } = router.query;
  return (
    <div className={styles.container}>
      <Head>
        <title>{name} - Wise Wheels</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <div className={styles.wheelContainer}>
        <div className={styles.imageSection}>
          <img src={picture} alt='' />
        </div>
        <div className={styles.infoSection}>
          <h1>{name}</h1>
          <p>Some Description</p>
          <div className={styles.buttonSection}>
            <button className={styles.button}>Get It Now</button>
            <button className={styles.button2}>Share</button>
          </div>
        </div>
      </div>

      <div className={styles.bottomSection}>
        <h3>Feel Free to contact us for more information</h3>
        <button className={styles.button}>Contact Us</button>
      </div>

      <div className={styles.coverImage}>
        <Image src='/car8.PNG' width={1900} height={900} objectFit='cover' />
      </div>
      <Footer />
    </div>
  );
}

export default wheel;
