import Image from 'next/image';
import ApparelsList from '../components/Apparels/ApparelsList';
import Header from '../components/HeaderFooter/Header';
import styles from '../styles/Apparels/apparels.module.css';
import Head from 'next/head';
import Footer from '../components/HeaderFooter/Footer';
import { selectApparel } from '../slices/webStateSlice';
import { useSelector } from 'react-redux';

function apparels() {
  const image = useSelector(selectApparel);

  return (
    <div className={styles.container}>
      <Head>
        <title>Apparels - Wise Wheels</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <Header />
        <div className={styles.body}>
          <div className={styles.topSection}>
            <div className={styles.subSec}>
              <div>
                <h1>Apparel</h1>
                <p>
                  Lorem ipsum dolor sit amet consectetur adipisicing elit.
                  Ducimus eveniet quae reiciendis voluptatum dolorum repellat
                  quia reprehenderit ipsa quo, beatae cupiditate debitis, error
                  facilis aut rerum fuga tempore. Ab, cum?
                </p>
              </div>
              <img className={styles.image} src={image[0]?.picture} />
            </div>
          </div>
          <div className={styles.midSection}>
            <ApparelsList />
          </div>
        </div>
        <Footer />
      </main>
    </div>
  );
}

export default apparels;
