import styles from '../styles/FAQ/faq.module.css';
import SingleQuestion from '../components/FAQ/Question';
import Header from '../components/HeaderFooter/Header';
import Footer from '../components/HeaderFooter/Footer';

import { useState } from 'react';
import Head from 'next/head';
function Faq() {
  const [questions, setQuestions] = useState([
    {
      id: 1,
      title: 'Do I have to allow the use of cookies?',
      info: 'Unicorn vinyl poutine brooklyn, next level direct trade iceland. Shaman copper mug church-key coloring book, whatever poutine normcore fixie cred kickstarter post-ironic street art.',
    },
    {
      id: 2,
      title: 'How do I change my My Page password?',
      info: 'Coloring book forage photo booth gentrify lumber. Migas chillwave poutine synth shoreditch, enamel pin thundercats fashion axe roof party polaroid chartreuse.',
    },
    {
      id: 3,
      title: 'What is BankID?',
      info: 'Enamel pin fam sustainable woke whatever venmo. Authentic asymmetrical put a bird on it, lumbersexual activated charcoal kinfolk banjo cred pickled sartorial.',
    },
    {
      id: 4,
      title: 'Whose birth number can I use?',
      info: 'Edison bulb direct trade gentrify beard lo-fi seitan sustainable roof party franzen occupy squid. Knausgaard cronut succulents, scenester readymade shabby chic lyft. Copper mug meh vegan gentrify.',
    },
    {
      id: 5,
      title: 'When do I recieve a password ordered by letter?',
      info: 'Locavore franzen fashion axe live-edge neutra irony synth af tilde shabby chic man braid chillwave waistcoat copper mug messenger bag. Banjo snackwave blog, microdosing thundercats migas vaporware viral lo-fi seitan ',
    },
  ]);
  return (
    <div>
      <Head>
        <title>FAQs - Wise Wheels</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <Header />
        <div className={styles.body}>
          <h1>Contact Us</h1>
          <div className={styles.contactContainer}>
            <h1>Let's Have A Chat</h1>
            <p>
              We know that your car build is important to you that's why we have
              this portal for you. If you have a question or need help with your
              car mods, feel free to contac us bellow. We'll be happy to assist
              you with your car mods here at Wise Wheels.
            </p>
            <div className={styles.email}>
              <h4>Email</h4>
              <input
                required
                placeholder='Please Enter Your Email'
                type='email'
              />
            </div>
            <div className={styles.text}>
              <h4>Inqury</h4>
              <textarea
                required
                placeholder='Please Enter Your Inquiry'
                name=''
                id=''
                cols='50'
                rows='10'
              ></textarea>
            </div>
            <button className={styles.button}>Send It</button>
          </div>
          <h1>FAQs</h1>
          <div className={styles.container}>
            <section className={styles.info}>
              {questions.map((question) => {
                return (
                  <SingleQuestion
                    key={question.id}
                    {...question}
                  ></SingleQuestion>
                );
              })}
            </section>
          </div>
        </div>
        <Footer />
      </main>
    </div>
  );
}

export default Faq;
