import Image from 'next/image';
import Header from '../components/HeaderFooter/Header';
import PartsList from '../components/Parts/PartsList';
import styles from '../styles/Parts/parts.module.css';
import Footer from '../components/HeaderFooter/Footer';

import Head from 'next/head';
function parts() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Parts - Wise Wheels</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <main>
        <Header />
        <div className={styles.body}>
          <div className={styles.topSection}>
            <div className={styles.subSec}>
              <div>
                <h1>Parts</h1>
                <p>
                  Lorem ipsum dolor sit amet consectetur adipisicing elit.
                  Ducimus eveniet quae reiciendis voluptatum dolorum repellat
                  quia reprehenderit ipsa quo, beatae cupiditate debitis, error
                  facilis aut rerum fuga tempore. Ab, cum?
                </p>
              </div>
              <img className={styles.image} src='/car6.jpg' />
            </div>
          </div>
          <div className={styles.midSection}>
            <PartsList />
          </div>
        </div>
        <Footer />
      </main>
    </div>
  );
}

export default parts;
